# Generated by Django 4.2 on 2023-10-25 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_productmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='last_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
