# Generated by Django 4.2 on 2023-10-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_productmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
